# Trend Analysis MCP Agent - SAM Configuration
log:
  stdout_log_level: INFO
  log_file_level: INFO
  log_file: trend-analysis-mcp-agent.log

!include ../shared_config.yaml

apps:
  - name: trend-analysis-mcp-agent_app
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: ${NAMESPACE} 
      supports_streaming: true
      agent_name: "TrendAnalysisMCPAgent"
      display_name: "Trend Analysis MCP Agent"
      model: *analysis_model 

      instruction: |
        You are a Trend Analysis Agent that uses MCP tools to analyze content for trending patterns, 
        viral mechanics, and artificial amplification.
        
        Your primary tool is analyze_trend_patterns which provides:
        - Viral pattern detection and engagement velocity analysis
        - Hashtag trending analysis and artificial amplification detection
        - Organic vs paid classification with confidence levels
        - Platform-specific trend analysis across social media
        
        Always use the analyze_trend_patterns tool for analysis requests and return structured results
        with trend manipulation scores, confidence levels, and detailed evidence of artificial amplification.

      inject_system_purpose: true
      inject_response_format: true
      session_service: *default_session_service
      artifact_service: *default_artifact_service
      artifact_handling_mode: "reference" 
      enable_embed_resolution: true 

      tools: 
        - group_name: artifact_management
          tool_type: builtin-group
        - group_name: trend_analysis_mcp
          tool_type: mcp
          connection_params:
            url: "http://localhost:8002"

      agent_card:
        description: "MCP-powered agent for analyzing trending patterns and viral manipulation using FastMCP tools"
        defaultInputModes: [text]
        defaultOutputModes: [text]
        skills:
          - id: "viral_pattern_detection"
            name: "Viral Pattern Detection"
            description: "Detect artificial viral patterns and trending manipulation"
          - id: "engagement_analysis"
            name: "Engagement Analysis"
            description: "Analyze engagement velocity and amplification patterns"
          - id: "trend_authenticity"
            name: "Trend Authenticity"
            description: "Assess authenticity of trending content and organic growth"

      agent_card_publishing: 
        interval_seconds: 30
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: ["OrchestratorAgent", "ScoreAggregatorMCPAgent", "BotDetectionMCPAgent"]
        request_timeout_seconds: 60
