# Plugin Metadata:
# Name: sam-event-mesh-gateway
# Version: 0.1.0
# Description: Solace Agent Mesh Gateway plugin for integrating with Solace PubSub+ event brokers.
# Author: SolaceLabs <solacelabs@solace.com>

log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: signalzero-event-mesh.log

# To use the `shared_config.yaml` file, uncomment the following line and remove the `shared_config` section below.
!include ../shared_config.yaml

apps:
  - name: signalzero-event-mesh-app
    app_module: sam_event_mesh_gateway.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}" 
      gateway_id: "event-mesh-gw-01" # Unique ID for this gateway instance

      artifact_service: *default_artifact_service
      authorization_service:
        type: "none" # Or "default_rbac"
      default_user_identity: "anonymous_event_mesh_user" # If no identity from event
      
      # --- Event Mesh Gateway Specific Parameters ---
      event_mesh_broker_config: # For the data plane Solace client
        broker_url: ${SOLACE_BROKER_URL, ws://localhost:8080} # Use same as control plane
        broker_vpn: ${SOLACE_BROKER_VPN, default}
        broker_username: ${SOLACE_BROKER_USERNAME, default}
        broker_password: ${SOLACE_BROKER_PASSWORD, default}
        # Other data plane client settings (e.g., client_name, reconnection_strategy)

      ##############################
      # 1. UPDATE REQUIRED - START #
      ##############################
      
      event_handlers: # List of handlers for incoming Solace messages
        # Analysis Request Handler - Routes analysis requests to appropriate agents
        - name: "analysis_request_handler"
          subscriptions:
            - topic: "signalzero/analysis/request/>"
              qos: 1
          input_expression: "template:Analyze query: {{text://input.payload:query}}. Analysis ID: {{text://input.payload:analysisId}}, User ID: {{text://input.payload:userId}}. Return comprehensive Reality Score analysis."
          payload_encoding: "utf-8"
          payload_format: "json"
          target_agent_name: "BotDetectionMCPAgent"
          on_success: "analysis_response_handler"
          on_error: "error_response_handler"
          user_identity_expression: "input.payload:userId"
          forward_context:
            analysis_id: "input.payload:analysisId"
            user_id: "input.payload:userId"
            correlation_id: "input.user_properties:correlation_id"

        # Bot Detection Handler - Processes bot detection requests
        - name: "bot_detection_handler"
          subscriptions:
            - topic: "signalzero/agent/bot-detector/request"
              qos: 1
          input_expression: "template:Analyze query: {{text://input.payload:query}} for bot activity. Analysis ID: {{text://input.payload:analysisId}}. Focus on automated patterns and bot percentage."
          payload_encoding: "utf-8"
          payload_format: "json"
          target_agent_name: "BotDetectionMCPAgent"
          on_success: "bot_detection_response_handler"
          on_error: "error_response_handler"
          forward_context:
            analysis_id: "input.payload:analysisId"
            agent_type: "static:bot-detector"

        # Trend Analysis Handler - Processes trend analysis requests
        - name: "trend_analysis_handler"
          subscriptions:
            - topic: "signalzero/agent/trend-analyzer/request"
              qos: 1
          input_expression: "template:Analyze trending patterns for query: {{text://input.payload:query}}. Analysis ID: {{text://input.payload:analysisId}}. Identify viral mechanics and trend authenticity."
          payload_encoding: "utf-8"
          payload_format: "json"
          target_agent_name: "TrendAnalysisMCPAgent"
          on_success: "trend_analysis_response_handler"
          on_error: "error_response_handler"
          forward_context:
            analysis_id: "input.payload:analysisId"
            agent_type: "static:trend-analyzer"

        # Review Validation Handler - Processes review validation requests
        - name: "review_validation_handler"
          subscriptions:
            - topic: "signalzero/agent/review-validator/request"
              qos: 1
          input_expression: "template:Validate review authenticity for query: {{text://input.payload:query}}. Analysis ID: {{text://input.payload:analysisId}}. Check for fake reviews and authentic engagement."
          payload_encoding: "utf-8"
          payload_format: "json"
          target_agent_name: "ReviewValidatorMCPAgent"
          on_success: "review_validation_response_handler"
          on_error: "error_response_handler"
          forward_context:
            analysis_id: "input.payload:analysisId"
            agent_type: "static:review-validator"

        # Promotion Detection Handler - Processes paid promotion detection requests
        - name: "promotion_detection_handler"
          subscriptions:
            - topic: "signalzero/agent/promotion-detector/request"
              qos: 1
          input_expression: "template:Detect paid promotions for query: {{text://input.payload:query}}. Analysis ID: {{text://input.payload:analysisId}}. Look for sponsored content and promotional indicators."
          payload_encoding: "utf-8"
          payload_format: "json"
          target_agent_name: "PaidPromotionMCPAgent"
          on_success: "promotion_detection_response_handler"
          on_error: "error_response_handler"
          forward_context:
            analysis_id: "input.payload:analysisId"
            agent_type: "static:promotion-detector"

        # Score Aggregation Handler - Processes final score aggregation
        - name: "score_aggregation_handler"
          subscriptions:
            - topic: "signalzero/agent/score-aggregator/request"
              qos: 1
          input_expression: "template:Aggregate final Reality Score for query: {{text://input.payload:query}}. Analysis ID: {{text://input.payload:analysisId}}. Combine all agent results."
          payload_encoding: "utf-8"
          payload_format: "json"
          target_agent_name: "ScoreAggregatorMCPAgent"
          on_success: "score_aggregation_response_handler"
          on_error: "error_response_handler"
          forward_context:
            analysis_id: "input.payload:analysisId"
            agent_type: "static:score-aggregator"

  # Example of a second event handler, commented out
  #       - name: "text_event_to_specific_agent"
  #         subscriptions:
  #           - topic: "external/systemB/events/text/>"
  #         input_expression: "template:User query from System B: {{text://input.payload}}"
  #         payload_encoding: "utf-8" # Or "none" if payload is already string
  #         payload_format: "text"
  #         on_success: "text_response_to_systemB"
  #         target_agent_name_expression: "static:TextAnalysisAgent" # Example of static via expression

      output_handlers: # Optional: List of handlers for publishing A2A responses
        # Main Analysis Response Handler - Publishes results back to analysis response topic
        - name: "analysis_response_handler"
          max_file_size_for_base64_bytes: 5242880 # 5MB limit for embedded files
          topic_expression: "template:signalzero/analysis/response/{{text://user_data.forward_context:user_id}}/{{text://user_data.forward_context:analysis_id}}"
          payload_expression: "task_response:text"
          payload_encoding: "utf-8"
          payload_format: "json"

        # Bot Detection Response Handler
        - name: "bot_detection_response_handler"
          topic_expression: "static:signalzero/agent/bot-detector/response"
          payload_expression: "task_response:text"
          payload_encoding: "utf-8"
          payload_format: "json"

        # Trend Analysis Response Handler
        - name: "trend_analysis_response_handler"
          topic_expression: "static:signalzero/agent/trend-analyzer/response"
          payload_expression: "task_response:text"
          payload_encoding: "utf-8"
          payload_format: "json"

        # Review Validation Response Handler
        - name: "review_validation_response_handler"
          topic_expression: "static:signalzero/agent/review-validator/response"
          payload_expression: "task_response:text"
          payload_encoding: "utf-8"
          payload_format: "json"

        # Promotion Detection Response Handler
        - name: "promotion_detection_response_handler"
          topic_expression: "static:signalzero/agent/promotion-detector/response"
          payload_expression: "task_response:text"
          payload_encoding: "utf-8"
          payload_format: "json"

        # Score Aggregation Response Handler
        - name: "score_aggregation_response_handler"
          topic_expression: "template:signalzero/updates/score/{{text://user_data.forward_context:analysis_id}}"
          payload_expression: "task_response:text"
          payload_encoding: "utf-8"
          payload_format: "json"

        # Error Response Handler - Generic error handler for all failed operations
        - name: "error_response_handler"
          topic_expression: "template:signalzero/updates/status/{{text://user_data.forward_context:analysis_id}}"
          payload_expression: "task_response:a2a_task_response.error"
          payload_encoding: "utf-8"
          payload_format: "json"

        # Status Update Handler - For real-time status updates
        - name: "status_update_handler"
          topic_expression: "template:signalzero/updates/status/{{text://user_data.forward_context:analysis_id}}"
          payload_expression: "task_response:text"
          payload_encoding: "utf-8"
          payload_format: "json"

  # Example of a second output handler, commented out
  #       - name: "text_response_to_systemB"
  #         topic_expression: "template:external/systemB/responses/{{text://task_response:id}}"
  #         payload_expression: "task_response:status.message.parts.0.text" # Direct access
  #         payload_encoding: "utf-8"
  #         payload_format: "text"

      ############################
      # 1. UPDATE REQUIRED - END #
      ############################
